### ISSUE TITLE
Camera Playing Around

### ISSUE THREAD

**Issue by JessicaKline** [The-Charge/PowerUp2018#16]
Change the resolution so it's more detailed and stuff

**Comment by sreeramsa** [comment]
https://wpilib.screenstepslive.com/s/currentCS/m/vision/l/669166-using-the-cameraserver-on-the-roborio

**Comment by ghost** [comment]
https://wpilib.screenstepslive.com/s/4485/m/24194/l/144985-configuring-an-axis-camera
